import type { RuleCatalog } from "./schema";
import { validateRuleCatalog } from "./schema";

export const ruleCatalog: RuleCatalog = {
  moves: [
    // ========== 外功 WG001-WG009 ==========
    {
      id: "WG001",
      name: "破浪横刀",
      category: "外功",
      subCategory: "主攻",
      tier: "俗家",
      designGrade: "C",
      yinYangLabel: "少阳",
      timing: "正式出手",
      formPosition: "起式",
      minimumDice: 2,
      qiRequirement: "至少1阳",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "失势"],
      hardPrerequisite: "无",
      rangeAndEquipment: "近身人物目标；主手刀或同类短兵",
      baseEffect: "造成气血4点",
      slotTriggers: ["阳值≥7：追加气血3点", "合值≥10：目标退距1档", "阴阳差≥5：自身破口1层"],
      afterMomentum: "阳盛",
      resourceFlow: "已用常规气骰入息库",
      hasIntercept: true,
      hasReact: true,
    },
    {
      id: "WG002",
      name: "回潮压刃",
      category: "外功",
      subCategory: "主攻",
      tier: "俗家",
      designGrade: "B",
      yinYangLabel: "少阳",
      timing: "正式出手",
      formPosition: "承式",
      minimumDice: 3,
      qiRequirement: "至少1阴1阳",
      momentumRequirement: "宽势",
      allowedMomentum: ["阳盛", "合势", "圆融"],
      hardPrerequisite: "无",
      rangeAndEquipment: "近身人物目标；主手刀",
      baseEffect: "造成气血5点",
      slotTriggers: ["阳值≥8：追加气血3点", "合值≥12：目标迟滞1层", "阴阳差≥5：自身转入失势"],
      afterMomentum: "合势",
      resourceFlow: "已用常规气骰入息库",
      hasIntercept: true,
      hasReact: false,
    },
    {
      id: "WG003",
      name: "分涛断势",
      category: "外功",
      subCategory: "拆招",
      tier: "行家",
      designGrade: "B",
      yinYangLabel: "中平",
      timing: "正式出手",
      formPosition: "转式",
      minimumDice: 3,
      qiRequirement: "至少1阴1阳",
      momentumRequirement: "中势",
      allowedMomentum: ["阴盛", "合势", "圆融"],
      hardPrerequisite: "无",
      rangeAndEquipment: "近身人物目标；刀、剑、短兵均可",
      baseEffect: "目标当前势转入失势，或关闭目标1项轻前置许可",
      slotTriggers: ["阴值≥8：目标锁气中1枚最低点气骰入息库", "合值≥14：目标本轮不能声明强招", "阴阳差≥6：自身迟滞1层"],
      afterMomentum: "阴盛",
      resourceFlow: "已用常规气骰入息库",
      hasIntercept: true,
      hasReact: false,
    },
    {
      id: "WG004",
      name: "收刀归息",
      category: "外功",
      subCategory: "收式",
      tier: "俗家",
      designGrade: "B",
      yinYangLabel: "中平",
      timing: "正式出手",
      formPosition: "收式",
      minimumDice: 2,
      qiRequirement: "任意气性",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融"],
      hardPrerequisite: "无",
      rangeAndEquipment: "自己；需持刀或可收束姿态",
      baseEffect: "自身破口-1或迟滞-1（二选一）",
      slotTriggers: ["阴值≥7：额外降低1层轻交锋状态", "合值≥10：取回1枚最低阶已用常规气骰入气海；限每轮1次", "阴阳差≥5：自身失势"],
      afterMomentum: "圆融",
      resourceFlow: "未回收的已用气骰入息库",
      hasIntercept: false,
      hasReact: true,
    },
    {
      id: "WG005",
      name: "沧浪一线",
      category: "外功",
      subCategory: "绝式",
      tier: "行家",
      designGrade: "A",
      yinYangLabel: "少阳",
      timing: "正式出手",
      formPosition: "绝式",
      minimumDice: 6,
      qiRequirement: "至少3阳2阴",
      momentumRequirement: "单势",
      allowedMomentum: ["圆融"],
      hardPrerequisite: "无",
      rangeAndEquipment: "近身人物目标；主手刀；目标线明确",
      baseEffect: "造成气血10点",
      slotTriggers: ["阳值≥16：追加气血=爆发×1", "合值≥22：目标失衡2层", "阴阳差≥7：自身崩势"],
      afterMomentum: "未触发风险为圆融；触发风险为崩势",
      resourceFlow: "全部入息库；无普通回气",
      hasIntercept: false,
      hasReact: false,
    },
    {
      id: "WG006",
      name: "燕回侧步",
      category: "外功",
      subCategory: "身法",
      tier: "俗家",
      designGrade: "C",
      yinYangLabel: "少阴",
      timing: "正式出手",
      formPosition: "起式",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "合势", "失势", "圆融"],
      hardPrerequisite: "无",
      rangeAndEquipment: "自己；近身或相邻距离",
      baseEffect: "移步1档或取得遮蔽",
      slotTriggers: ["阴值≥7：不触发普通追身机会", "合值≥10：关闭一条普通目标线到本动作结束", "阴阳差≥5：自身迟滞1层"],
      afterMomentum: "阴盛",
      resourceFlow: "已用常规气骰入息库",
      hasIntercept: true,
      hasReact: true,
    },
    {
      id: "WG007",
      name: "回身护肩",
      category: "外功",
      subCategory: "护人",
      tier: "俗家",
      designGrade: "B",
      yinYangLabel: "少阴",
      timing: "正式出手",
      formPosition: "收式",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "合势", "圆融"],
      hardPrerequisite: "无",
      rangeAndEquipment: "自己或相邻同伴；需可介入目标线",
      baseEffect: "为目标建立护人许可至本轮结束",
      slotTriggers: ["阴值≥7：护人许可额外抵消气血2点", "合值≥10：可承接一项轻状态", "阴阳差≥5：自身迟滞1层"],
      afterMomentum: "不改势",
      resourceFlow: "已用常规气骰入息库",
      hasIntercept: false,
      hasReact: true,
    },
    {
      id: "WG008",
      name: "截腕挑锋",
      category: "外功",
      subCategory: "拆招",
      tier: "俗家",
      designGrade: "B",
      yinYangLabel: "少阴",
      timing: "正式出手",
      formPosition: "转式",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "合势", "失势"],
      hardPrerequisite: "无",
      rangeAndEquipment: "近身目标；空手、短兵或副手兵器",
      baseEffect: "目标本轮持械许可受扰：下一次持械招最低投入+1枚气骰",
      slotTriggers: ["阴值≥7：目标破口1层", "合值≥10：目标副手许可关闭至本轮结束", "阴阳差≥5：自身破口1层"],
      afterMomentum: "阴盛",
      resourceFlow: "已用常规气骰入息库",
      hasIntercept: true,
      hasReact: false,
    },
    {
      id: "WG009",
      name: "夺器压腕",
      category: "外功",
      subCategory: "拆招",
      tier: "行家",
      designGrade: "B",
      yinYangLabel: "少阴",
      timing: "正式出手",
      formPosition: "转式",
      minimumDice: 4,
      qiRequirement: "至少2阴",
      momentumRequirement: "中势",
      allowedMomentum: ["阴盛", "圆融"],
      hardPrerequisite: "无",
      rangeAndEquipment: "近身；空手、短兵或软兵；目标持械",
      baseEffect: "目标武器进入脱手威胁；下一次依赖该武器的动作需额外投入1枚气骰",
      slotTriggers: ["阴值≥9：目标武器脱手落在近身区域", "合值≥14：同时关闭目标本轮持械许可", "阴阳差≥6：自身破口1层"],
      afterMomentum: "阴盛",
      resourceFlow: "已用常规气骰入息库",
      hasIntercept: true,
      hasReact: false,
    },

    // ========== 法门 FM001-FM005 ==========
    {
      id: "FM001",
      name: "听痕辨路",
      category: "法门",
      subCategory: "查探",
      tier: "俗家",
      designGrade: "C",
      yinYangLabel: "少阴",
      timing: "正式出手/情景",
      formPosition: "无",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "无势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融", "崩势", "失势"],
      hardPrerequisite: "无",
      rangeAndEquipment: "道路、房间、尸身周边或机关痕迹",
      baseEffect: "取得1条明确痕迹；解密+1",
      slotTriggers: ["阴值≥7：确认痕迹方向或新旧", "合值≥10：危机-1", "阴阳差≥5：危机+1，并记录误判线索名"],
      afterMomentum: "不改势",
      resourceFlow: "已用常规气骰入息库",
      hasIntercept: true,
      hasReact: false,
    },
    {
      id: "FM002",
      name: "行气解穴",
      category: "法门",
      subCategory: "行气",
      tier: "行家",
      designGrade: "B",
      yinYangLabel: "中平",
      timing: "正式出手",
      formPosition: "无",
      minimumDice: 3,
      qiRequirement: "至少1原始，或阴阳各1",
      momentumRequirement: "无势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融", "崩势", "失势"],
      hardPrerequisite: "无",
      rangeAndEquipment: "自己或相邻同伴；需接触或行气许可；目标有封穴",
      baseEffect: "指定封穴-1层",
      slotTriggers: ["阴值≥8：封穴影响的1枚气骰本轮可正常回收", "合值≥12：封穴再-1层", "阴阳差≥5：施法者失势"],
      afterMomentum: "不改势",
      resourceFlow: "已用常规气骰入息库",
      hasIntercept: false,
      hasReact: true,
    },
    {
      id: "FM003",
      name: "压场问话",
      category: "法门",
      subCategory: "交涉",
      tier: "俗家",
      designGrade: "C",
      yinYangLabel: "少阳",
      timing: "正式出手/情景",
      formPosition: "无",
      minimumDice: 2,
      qiRequirement: "至少1阳",
      momentumRequirement: "无势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融", "崩势", "失势"],
      hardPrerequisite: "无",
      rangeAndEquipment: "人物或小群体；同场可闻",
      baseEffect: "危机-1，或取得一句明确态度",
      slotTriggers: ["阳值≥7：写入\"暂时压住场面\"许可", "合值≥10：取得一项可追问入口", "阴阳差≥5：关系事实写入\"冒犯某人\""],
      afterMomentum: "不改势",
      resourceFlow: "已用常规气骰入息库",
      hasIntercept: true,
      hasReact: true,
    },
    {
      id: "FM004",
      name: "简药止血",
      category: "法门",
      subCategory: "医药",
      tier: "俗家",
      designGrade: "C",
      yinYangLabel: "少阴",
      timing: "正式出手/情景",
      formPosition: "无",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "无势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融", "崩势", "失势"],
      hardPrerequisite: "无",
      rangeAndEquipment: "自己或接触目标；有药物、布条或可替代材料",
      baseEffect: "流血-1，或气血+2（二选一）",
      slotTriggers: ["阴值≥7：额外气血+2", "合值≥10：流血再-1", "阴阳差≥5：药物资源消耗+1"],
      afterMomentum: "不改势",
      resourceFlow: "已用常规气骰入息库；药物按条目消耗",
      hasIntercept: false,
      hasReact: true,
    },
    {
      id: "FM005",
      name: "残页参悟",
      category: "法门",
      subCategory: "读谱",
      tier: "行家",
      designGrade: "B",
      yinYangLabel: "中平",
      timing: "整备/情景",
      formPosition: "无",
      minimumDice: 3,
      qiRequirement: "至少1原始",
      momentumRequirement: "无势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融", "崩势", "失势"],
      hardPrerequisite: "无",
      rangeAndEquipment: "谱本、残页、口诀或战后招痕",
      baseEffect: "记忆进度+1",
      slotTriggers: ["阴值≥8：排除一项误读", "合值≥12：打开整理许可", "阴阳差≥5：记录\"疑义待校\""],
      afterMomentum: "不改势",
      resourceFlow: "整备气骰按场景规则处理",
      hasIntercept: false,
      hasReact: false,
    },
  ],

  responses: [
    // ========== 响应挂载 RG001-RG015 ==========
    {
      id: "RG001",
      moveId: "WG001",
      name: "破浪横刀",
      responseType: "截击",
      canCallIndependently: true,
      timing: "宣言后、配置前",
      minimumDice: 2,
      qiRequirement: "至少1阳",
      momentumRequirement: "宽势",
      allowedMomentum: ["阳盛", "合势", "失势"],
      rangeAndEquipment: "近身；主手刀；目标声明近身外功",
      baseEffect: "目标1枚锁气本次不能进入阳槽",
      slotTriggers: ["阳值≥7：该锁气改入息库", "合值≥10：目标本次基础效果-2气血", "阴阳差≥5：自身破口1层"],
      afterMomentum: "阳盛",
      resourceFlow: "截击气骰入息库",
      constraints: "只处理锁气与基础效果，不自动造成主用法伤害",
    },
    {
      id: "RG002",
      moveId: "WG001",
      name: "破浪横刀",
      responseType: "应招",
      canCallIndependently: true,
      timing: "成招后、落果前",
      minimumDice: 2,
      qiRequirement: "至少1阳",
      momentumRequirement: "宽势",
      allowedMomentum: ["阳盛", "合势", "圆融"],
      rangeAndEquipment: "自己成为近身气血目标；主手刀或副手刀",
      baseEffect: "抵消气血3点",
      slotTriggers: ["阳值≥7：额外抵消气血2点", "合值≥10：可将自己退距1档", "阴阳差≥5：自身迟滞1层"],
      afterMomentum: "不改势",
      resourceFlow: "应招气骰入息库",
      constraints: "应招只处理自身目标线",
    },
    {
      id: "RG003",
      moveId: "WG002",
      name: "回潮压刃",
      responseType: "截击",
      canCallIndependently: true,
      timing: "宣言后、配置前",
      minimumDice: 3,
      qiRequirement: "至少1阴1阳",
      momentumRequirement: "中势",
      allowedMomentum: ["阳盛", "合势"],
      rangeAndEquipment: "近身；主手刀；目标正在退距或换位",
      baseEffect: "关闭目标本次退距附加效果",
      slotTriggers: ["阳值≥8：目标迟滞1层", "合值≥12：目标锁气中1枚最低点气骰入息库", "阴阳差≥5：自身失势"],
      afterMomentum: "合势",
      resourceFlow: "截击气骰入息库",
      constraints: "中级截击要求较窄势范围",
    },
    {
      id: "RG004",
      moveId: "WG003",
      name: "分涛断势",
      responseType: "截击",
      canCallIndependently: true,
      timing: "宣言后、配置前",
      minimumDice: 3,
      qiRequirement: "至少2阴",
      momentumRequirement: "中势",
      allowedMomentum: ["阴盛", "圆融"],
      rangeAndEquipment: "近身或相邻目标线；目标宣言依赖势条件的中强招式",
      baseEffect: "目标本次势条件视为不满足",
      slotTriggers: ["阴值≥8：目标由当前势转入失势", "合值≥14：目标本次动作不成招", "阴阳差≥6：自身迟滞1层"],
      afterMomentum: "阴盛",
      resourceFlow: "截击气骰入息库",
      constraints: "强截击体现势生态位，专门处理势前置",
    },
    {
      id: "RG005",
      moveId: "WG004",
      name: "收刀归息",
      responseType: "应招",
      canCallIndependently: true,
      timing: "成招后、落果前",
      minimumDice: 2,
      qiRequirement: "任意气性",
      momentumRequirement: "宽势",
      allowedMomentum: ["合势", "圆融", "阴盛", "阳盛"],
      rangeAndEquipment: "自己成为轻状态或破口目标；需可收束姿态",
      baseEffect: "抵消1层破口或迟滞",
      slotTriggers: ["阴值≥7：再抵消1层轻状态", "合值≥10：取回1枚最低阶已用常规气骰入气海；限每轮1次", "阴阳差≥5：自身失势"],
      afterMomentum: "圆融",
      resourceFlow: "应招气骰入息库；取回气骰入气海",
      constraints: "这类应招偏自保和回收，不反击",
    },
    {
      id: "RG006",
      moveId: "WG006",
      name: "燕回侧步",
      responseType: "截击",
      canCallIndependently: true,
      timing: "宣言后、配置前",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "合势", "失势"],
      rangeAndEquipment: "目标宣言追身、锁定或近身压迫；自己可移动",
      baseEffect: "关闭目标本次追身或锁定附加效果",
      slotTriggers: ["阴值≥7：自己退距1档", "合值≥10：本次不触发普通追击", "阴阳差≥5：自身迟滞1层"],
      afterMomentum: "阴盛",
      resourceFlow: "截击气骰入息库",
      constraints: "身法截击不取消所有伤害，只处理追身/锁定",
    },
    {
      id: "RG007",
      moveId: "WG006",
      name: "燕回侧步",
      responseType: "应招",
      canCallIndependently: true,
      timing: "成招后、落果前",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "合势", "圆融", "失势"],
      rangeAndEquipment: "自己成为近身气血或位置结果目标；需有可移动空间",
      baseEffect: "抵消气血2点或取消退距结果（二选一）",
      slotTriggers: ["阴值≥7：额外抵消气血2点", "合值≥10：自己取得遮蔽", "阴阳差≥5：自身迟滞1层"],
      afterMomentum: "不改势",
      resourceFlow: "应招气骰入息库",
      constraints: "可作为低阶通用身法应招",
    },
    {
      id: "RG008",
      moveId: "WG007",
      name: "回身护肩",
      responseType: "应招",
      canCallIndependently: true,
      timing: "成招后、落果前",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "合势", "圆融"],
      rangeAndEquipment: "相邻同伴所在目标线受气血结果；自己可介入",
      baseEffect: "抵消该目标线气血4点",
      slotTriggers: ["阴值≥7：额外抵消气血3点", "合值≥10：自己可承接该目标线剩余气血结果", "阴阳差≥5：自身迟滞1层"],
      afterMomentum: "不改势",
      resourceFlow: "应招气骰入息库",
      constraints: "护人应招挂载在护人招式，不再单列成独立泛用招",
    },
    {
      id: "RG009",
      moveId: "WG008",
      name: "截腕挑锋",
      responseType: "截击",
      canCallIndependently: true,
      timing: "宣言后、配置前",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "合势", "失势"],
      rangeAndEquipment: "近身；对方依赖手中兵器宣言",
      baseEffect: "目标1枚锁气本次不能进入阳槽",
      slotTriggers: ["阴值≥7：该气骰改入息库", "合值≥10：目标本次失去持械许可", "阴阳差≥5：自身破口1层"],
      afterMomentum: "阴盛",
      resourceFlow: "截击气骰入息库",
      constraints: "典型挂载截击，处理装备许可",
    },
    {
      id: "RG010",
      moveId: "WG009",
      name: "夺器压腕",
      responseType: "截击",
      canCallIndependently: true,
      timing: "宣言后、配置前",
      minimumDice: 4,
      qiRequirement: "至少2阴",
      momentumRequirement: "中势",
      allowedMomentum: ["阴盛", "圆融"],
      rangeAndEquipment: "近身；目标宣言持械中强招式；目标武器未固定",
      baseEffect: "目标装备许可关闭至本次动作结束",
      slotTriggers: ["阴值≥9：目标武器脱手落在近身区域", "合值≥14：目标本次动作不成招", "阴阳差≥6：自身破口1层"],
      afterMomentum: "阴盛",
      resourceFlow: "截击气骰入息库",
      constraints: "强缴械截击要求势和高投入",
    },
    {
      id: "RG011",
      moveId: "FM001",
      name: "听痕辨路",
      responseType: "截击",
      canCallIndependently: true,
      timing: "宣言后、配置前",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "无势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融", "崩势", "失势"],
      rangeAndEquipment: "同一区域；目标正在隐匿、误导或掩盖痕迹",
      baseEffect: "关闭目标本次隐匿/误导的1项附加触发",
      slotTriggers: ["阴值≥7：解密+1", "合值≥10：危机-1", "阴阳差≥5：危机+1"],
      afterMomentum: "不改势",
      resourceFlow: "截击气骰入息库",
      constraints: "情景法门也可挂轻截击，但不应转成战斗万能反制",
    },
    {
      id: "RG012",
      moveId: "FM002",
      name: "行气解穴",
      responseType: "应招",
      canCallIndependently: true,
      timing: "成招后、落果前",
      minimumDice: 3,
      qiRequirement: "至少1原始",
      momentumRequirement: "无势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融", "崩势", "失势"],
      rangeAndEquipment: "自己或接触同伴即将获得封穴；需行气许可",
      baseEffect: "将本次封穴结果-1层",
      slotTriggers: ["阴值≥8：本轮该六根对应气骰不被封锁", "合值≥12：再降低1层封穴", "阴阳差≥5：施法者失势"],
      afterMomentum: "不改势",
      resourceFlow: "应招气骰入息库",
      constraints: "处理落果前封穴，不治疗",
    },
    {
      id: "RG013",
      moveId: "FM003",
      name: "压场问话",
      responseType: "截击",
      canCallIndependently: true,
      timing: "宣言后、配置前",
      minimumDice: 2,
      qiRequirement: "至少1阳",
      momentumRequirement: "无势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融", "崩势", "失势"],
      rangeAndEquipment: "同场可闻；目标正在煽动、威慑或号令",
      baseEffect: "目标本次情景法门的危机降低效果关闭",
      slotTriggers: ["阳值≥7：危机-1", "合值≥10：写入\"暂时压住场面\"许可", "阴阳差≥5：关系事实写入\"冒犯某人\""],
      afterMomentum: "不改势",
      resourceFlow: "截击气骰入息库",
      constraints: "只处理话术/号令类目标，不截击武器动作",
    },
    {
      id: "RG014",
      moveId: "FM003",
      name: "压场问话",
      responseType: "应招",
      canCallIndependently: true,
      timing: "成招后、落果前",
      minimumDice: 2,
      qiRequirement: "至少1阳",
      momentumRequirement: "无势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融", "崩势", "失势"],
      rangeAndEquipment: "自己或同伴即将承受交涉压力、恐吓或关系恶化",
      baseEffect: "取消1项轻关系恶化或危机+1",
      slotTriggers: ["阳值≥7：反写\"对方露怯\"事实", "合值≥10：获得1项追问入口", "阴阳差≥5：自身关系事实写入\"过激发言\""],
      afterMomentum: "不改势",
      resourceFlow: "应招气骰入息库",
      constraints: "交涉应招是情景响应，不是战斗应招",
    },
    {
      id: "RG015",
      moveId: "FM004",
      name: "简药止血",
      responseType: "应招",
      canCallIndependently: true,
      timing: "成招后、落果前",
      minimumDice: 2,
      qiRequirement: "至少1阴",
      momentumRequirement: "无势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融", "崩势", "失势"],
      rangeAndEquipment: "接触目标即将获得流血或气血伤害；有材料",
      baseEffect: "本次气血结果-2，或流血结果-1层（二选一）",
      slotTriggers: ["阴值≥7：额外气血结果-2", "合值≥10：流血再-1层", "阴阳差≥5：药物资源消耗+1"],
      afterMomentum: "不改势",
      resourceFlow: "应招气骰入息库；材料按条目消耗",
      constraints: "药物结果必须明确，不写模糊稳定压力",
    },
  ],

  quickActions: [
    // ========== 便行 BX001-BX009 ==========
    {
      id: "BX001",
      name: "移步",
      type: "出手便行",
      timing: "自己回合",
      minimumDice: 1,
      qiRequirement: "任意",
      momentumRequirement: "无势",
      permission: "自己；合法空间",
      effect: "改变1档位置或取得明确站位",
      limit: "不能穿越强封锁；不能稳定脱离纠缠",
      resourceFlow: "已用气骰入息库",
    },
    {
      id: "BX002",
      name: "整身",
      type: "出手便行",
      timing: "自己回合",
      minimumDice: 1,
      qiRequirement: "任意",
      momentumRequirement: "无势",
      permission: "自己；姿态散乱、倒地、迟滞或轻破口",
      effect: "起身，或迟滞-1，或关闭轻破口（二选一）",
      limit: "不能清强状态",
      resourceFlow: "已用气骰入息库",
    },
    {
      id: "BX003",
      name: "援手",
      type: "出手便行",
      timing: "自己回合",
      minimumDice: 1,
      qiRequirement: "任意",
      momentumRequirement: "无势",
      permission: "相邻同伴或物件；无人强争夺",
      effect: "扶起、递物、拉离普通边缘（三选一）",
      limit: "不能替同伴应招",
      resourceFlow: "已用气骰入息库",
    },
    {
      id: "BX004",
      name: "取物",
      type: "出手便行",
      timing: "自己回合",
      minimumDice: 1,
      qiRequirement: "任意",
      momentumRequirement: "无势",
      permission: "可及且未被争夺的物件",
      effect: "取出或拾起一件可及物",
      limit: "有人争夺时改正式出手",
      resourceFlow: "已用气骰入息库",
    },
    {
      id: "BX005",
      name: "闭息",
      type: "出手便行",
      timing: "自己回合",
      minimumDice: 1,
      qiRequirement: "任意",
      momentumRequirement: "无势",
      permission: "烟尘、毒雾、水压等短压力",
      effect: "本轮抵抗一次轻环境压力",
      limit: "不能解毒，不能治疗",
      resourceFlow: "已用气骰入息库",
    },
    {
      id: "BX006",
      name: "调息",
      type: "出手便行",
      timing: "自己回合",
      minimumDice: 1,
      qiRequirement: "任意",
      momentumRequirement: "无势",
      permission: "息库有可回收常规气骰",
      effect: "按规则或条目从息库取回常规气骰，重掷入气海",
      limit: "只回气骰，不治疗、不清状态、不改势",
      resourceFlow: "息引入息库；取回气骰入气海",
    },
    {
      id: "BX007",
      name: "返照",
      type: "随手便行·特殊",
      timing: "获得行动机会且断气",
      minimumDice: 0,
      qiRequirement: "无",
      momentumRequirement: "无势",
      permission: "气池和气海均无可用常规气骰",
      effect: "取回1枚最低阶本命气骰，不重掷，保持原有点数入气海",
      limit: "保底回气，不提供攻击、防护、治疗",
      resourceFlow: "取回气骰入气海",
    },
    {
      id: "BX008",
      name: "短话示意",
      type: "随手便行",
      timing: "自己回合/响应回合",
      minimumDice: 0,
      qiRequirement: "无",
      momentumRequirement: "无势",
      permission: "同场可见或可闻同伴",
      effect: "说一句短话或作简单示意",
      limit: "不能完成交涉、威慑、命令",
      resourceFlow: "无",
    },
    {
      id: "BX009",
      name: "换握丢弃",
      type: "随手便行",
      timing: "自己回合/响应回合",
      minimumDice: 0,
      qiRequirement: "无",
      momentumRequirement: "无势",
      permission: "已持物件",
      effect: "换握已持武器或丢弃手中小物",
      limit: "不能拔新武器、不能夺物",
      resourceFlow: "无",
    },
  ],
};

export function assertRuleCatalogValid(): void {
  const result = validateRuleCatalog(ruleCatalog);
  if (!result.ok) {
    throw new Error(result.errors.join("；"));
  }
}
