export const scrollDiskAssets = {
  homeCard: "/assets/ui-scroll-disk/01_启动页主卡组件.png",
  roomPanel: "/assets/ui-scroll-disk/02_房间创建与加入组件.png",
  approved: {
    topNav: {
      compact: "/assets/ui-scroll-disk/crops/top_nav_compact.png",
      ornate: "/assets/ui-scroll-disk/crops/top_nav_ornate.png",
      plain: "/assets/ui-scroll-disk/crops/top_nav_plain.png",
    },
    bottomBar: {
      tabs: "/assets/ui-scroll-disk/crops/bottom_bar_tabs.png",
      resources: "/assets/ui-scroll-disk/crops/bottom_bar_resources.png",
      tools: "/assets/ui-scroll-disk/crops/bottom_bar_tools.png",
    },
    combatDisk: {
      jiaofeng: "/assets/ui-scroll-disk/crops/combat_disk_jiaofeng.png",
      jiugong: "/assets/ui-scroll-disk/crops/combat_disk_jiugong.png",
      attack: "/assets/ui-scroll-disk/crops/combat_disk_attack.png",
    },
    actionCards: {
      qishou: "/assets/ui-scroll-disk/crops/action_card_qishou.png",
      lianzhao: "/assets/ui-scroll-disk/crops/action_card_lianzhao.png",
      juezhao: "/assets/ui-scroll-disk/crops/action_card_juezhao.png",
      jieji: "/assets/ui-scroll-disk/crops/action_card_jieji.png",
      yingzhao: "/assets/ui-scroll-disk/crops/action_card_yingzhao.png",
      fanzhao: "/assets/ui-scroll-disk/crops/action_card_fanzhao.png",
      zhoutian: "/assets/ui-scroll-disk/crops/action_card_zhoutian.png",
      panding: "/assets/ui-scroll-disk/crops/action_card_panding.png",
      yingyong: "/assets/ui-scroll-disk/crops/action_card_yingyong.png",
      lunci: "/assets/ui-scroll-disk/crops/action_card_lunci.png",
    },
    qiZones: {
      poolTitle: "/assets/ui-scroll-disk/crops/qi_pool_title.png",
      seaTitle: "/assets/ui-scroll-disk/crops/qi_sea_title.png",
      lockTitle: "/assets/ui-scroll-disk/crops/qi_lock_title.png",
      restTitle: "/assets/ui-scroll-disk/crops/qi_rest_title.png",
      tempTitle: "/assets/ui-scroll-disk/crops/temp_qi_title.png",
      poolPanel: "/assets/ui-scroll-disk/crops/qi_pool_panel.png",
      seaPanel: "/assets/ui-scroll-disk/crops/qi_sea_panel.png",
      lockPanel: "/assets/ui-scroll-disk/crops/qi_lock_panel.png",
      restPanel: "/assets/ui-scroll-disk/crops/qi_rest_panel.png",
      tempPanel: "/assets/ui-scroll-disk/crops/temp_qi_panel.png",
    },
    qiDiceCards: {
      yin: "/assets/ui-scroll-disk/crops/qi_die_yin_card.png",
      yang: "/assets/ui-scroll-disk/crops/qi_die_yang_card.png",
      raw: "/assets/ui-scroll-disk/crops/qi_die_raw_card.png",
      temp: "/assets/ui-scroll-disk/crops/qi_die_temp_card.png",
    },
    diceModal: {
      dark: "/assets/ui-scroll-disk/crops/dice_modal_dark.png",
      light: "/assets/ui-scroll-disk/crops/dice_modal_light.png",
      wide: "/assets/ui-scroll-disk/crops/dice_modal_wide.png",
    },
    diceResults: {
      single: "/assets/ui-scroll-disk/crops/dice_result_single.png",
      double: "/assets/ui-scroll-disk/crops/dice_result_double.png",
      multi: "/assets/ui-scroll-disk/crops/dice_result_multi.png",
    },
  },
  deferred: {
    qiTokens: "原拆分图中代币行靠边，自动裁切存在残缺；本轮不用于正式控件。",
    statusStrip: "作为势/状态风格参考，正式徽记仍用 CSS 胶囊避免误读。",
    wholeBoards: "整板总览与多组件板只作为审查来源，不直接上屏。",
  },
  placement: {
    topbar: "topNav.compact as subtle topbar background",
    bottomToolbar: "bottomBar.tools behind drawer toolbar",
    combatStage: "combatDisk.jiaofeng centered under Phaser canvas",
    qiPanel: "qi zone title crops as section labels; panel crops as low-opacity textures",
    actionCards: "approved action card crops as card texture backgrounds only",
    diceOverlay: "diceModal.light/wide as modal texture; diceResults as result texture",
  },
} as const;
