// 大梁江湖TRPG APP 图标路径映射 - 2026年6月20日
// Codex可直接复制到前端项目，如 src/assets/daliangIconMap.ts
export const DALIANG_ICON_MAP = {
  001_player_character: { label: '角色', category: 'core_navigation', png: '/assets/icons/png256/001_player_character_角色.png', webp: '/assets/icons/webp512/001_player_character_角色.webp', route: '玩家端/底部导航/角色页' },
  002_inventory: { label: '背包', category: 'core_navigation', png: '/assets/icons/png256/002_inventory_背包.png', webp: '/assets/icons/webp512/002_inventory_背包.webp', route: '玩家端/底部导航/背包页' },
  003_map: { label: '地图', category: 'core_navigation', png: '/assets/icons/png256/003_map_地图.png', webp: '/assets/icons/webp512/003_map_地图.webp', route: '玩家端/底部导航/地图页' },
  004_journal: { label: '记录', category: 'core_navigation', png: '/assets/icons/png256/004_journal_记录.png', webp: '/assets/icons/webp512/004_journal_记录.webp', route: '玩家端/底部导航/记录页' },
  005_world: { label: '世界', category: 'world_content', png: '/assets/icons/png256/005_world_世界.png', webp: '/assets/icons/webp512/005_world_世界.webp', route: '资料库/世界观页' },
  006_combat: { label: '交锋', category: 'combat_core', png: '/assets/icons/png256/006_combat_交锋.png', webp: '/assets/icons/webp512/006_combat_交锋.webp', route: '交锋辅助/主交锋页' },
  007_moves: { label: '招式', category: 'combat_core', png: '/assets/icons/png256/007_moves_招式.png', webp: '/assets/icons/webp512/007_moves_招式.webp', route: '交锋辅助/招式选择区' },
  008_response: { label: '响应', category: 'combat_core', png: '/assets/icons/png256/008_response_响应.png', webp: '/assets/icons/webp512/008_response_响应.webp', route: '交锋辅助/响应提示区' },
  009_qi_dice: { label: '气骰', category: 'qi_yin_yang', png: '/assets/icons/png256/009_qi_dice_气骰.png', webp: '/assets/icons/webp512/009_qi_dice_气骰.webp', route: '交锋辅助/气骰区' },
  010_yinyang: { label: '阴阳', category: 'qi_yin_yang', png: '/assets/icons/png256/010_yinyang_阴阳.png', webp: '/assets/icons/webp512/010_yinyang_阴阳.webp', route: '角色页/阴阳结构；交锋页/阴阳投入' },
  011_momentum: { label: '势', category: 'momentum', png: '/assets/icons/png256/011_momentum_势.png', webp: '/assets/icons/webp512/011_momentum_势.webp', route: '交锋辅助/势面区' },
  012_six_roots: { label: '六根', category: 'six_roots', png: '/assets/icons/png256/012_six_roots_六根.png', webp: '/assets/icons/webp512/012_six_roots_六根.webp', route: '角色页/六根与内功盘' },
  013_status: { label: '状态', category: 'combat_core', png: '/assets/icons/png256/013_status_状态.png', webp: '/assets/icons/webp512/013_status_状态.webp', route: '交锋辅助/状态栏' },
  014_neigong: { label: '内功', category: 'martial_arts', png: '/assets/icons/png256/014_neigong_内功.png', webp: '/assets/icons/webp512/014_neigong_内功.webp', route: '武学页/内功页' },
  015_waigong: { label: '外功', category: 'martial_arts', png: '/assets/icons/png256/015_waigong_外功.png', webp: '/assets/icons/webp512/015_waigong_外功.webp', route: '武学页/外功页' },
  016_equipment: { label: '装备', category: 'equipment', png: '/assets/icons/png256/016_equipment_装备.png', webp: '/assets/icons/webp512/016_equipment_装备.webp', route: '背包页/装备页' },
  017_settings: { label: '设置', category: 'system', png: '/assets/icons/png256/017_settings_设置.png', webp: '/assets/icons/webp512/017_settings_设置.webp', route: '系统/设置页' },
  018_yin_sheng: { label: '阴盛', category: 'momentum_state', png: '/assets/icons/png256/018_yin_sheng_阴盛.png', webp: '/assets/icons/webp512/018_yin_sheng_阴盛.webp', route: '交锋辅助/势面区' },
  019_yang_sheng: { label: '阳盛', category: 'momentum_state', png: '/assets/icons/png256/019_yang_sheng_阳盛.png', webp: '/assets/icons/webp512/019_yang_sheng_阳盛.webp', route: '交锋辅助/势面区' },
  020_he_shi: { label: '合势', category: 'momentum_state', png: '/assets/icons/png256/020_he_shi_合势.png', webp: '/assets/icons/webp512/020_he_shi_合势.webp', route: '交锋辅助/势面区' },
  021_yuan_rong: { label: '圆融', category: 'momentum_state', png: '/assets/icons/png256/021_yuan_rong_圆融.png', webp: '/assets/icons/webp512/021_yuan_rong_圆融.webp', route: '交锋辅助/势面区' },
  022_beng_kui: { label: '崩溃', category: 'momentum_state', png: '/assets/icons/png256/022_beng_kui_崩溃.png', webp: '/assets/icons/webp512/022_beng_kui_崩溃.webp', route: '交锋辅助/势面区' },
  023_shi_shi: { label: '失势', category: 'momentum_state', png: '/assets/icons/png256/023_shi_shi_失势.png', webp: '/assets/icons/webp512/023_shi_shi_失势.webp', route: '交锋辅助/势面区' },
  024_tiaoxi: { label: '调息', category: 'resource_loop', png: '/assets/icons/png256/024_tiaoxi_调息.png', webp: '/assets/icons/webp512/024_tiaoxi_调息.webp', route: '交锋辅助/资源循环区' },
  025_zhoutian: { label: '周天轮转', category: 'resource_loop', png: '/assets/icons/png256/025_zhoutian_周天轮转.png', webp: '/assets/icons/webp512/025_zhoutian_周天轮转.webp', route: '交锋辅助/资源循环区' },
  026_fanzhao: { label: '返照', category: 'resource_loop', png: '/assets/icons/png256/026_fanzhao_返照.png', webp: '/assets/icons/webp512/026_fanzhao_返照.webp', route: '交锋辅助/资源循环区' },
  027_qishou: { label: '起手', category: 'combat_move_type', png: '/assets/icons/png256/027_qishou_起手.png', webp: '/assets/icons/webp512/027_qishou_起手.webp', route: '交锋辅助/招式类型' },
  028_lianzhao: { label: '连招', category: 'combat_move_type', png: '/assets/icons/png256/028_lianzhao_连招.png', webp: '/assets/icons/webp512/028_lianzhao_连招.webp', route: '交锋辅助/招式类型' },
  029_juezhao: { label: '绝招', category: 'combat_move_type', png: '/assets/icons/png256/029_juezhao_绝招.png', webp: '/assets/icons/webp512/029_juezhao_绝招.webp', route: '交锋辅助/招式类型' },
  030_jieji: { label: '截击', category: 'combat_response', png: '/assets/icons/png256/030_jieji_截击.png', webp: '/assets/icons/webp512/030_jieji_截击.webp', route: '交锋辅助/响应阶段' },
  031_yingzhao: { label: '应招', category: 'combat_response', png: '/assets/icons/png256/031_yingzhao_应招.png', webp: '/assets/icons/webp512/031_yingzhao_应招.webp', route: '交锋辅助/响应阶段' },
  032_menpai: { label: '门派', category: 'world_content', png: '/assets/icons/png256/032_menpai_门派.png', webp: '/assets/icons/webp512/032_menpai_门派.webp', route: '资料库/门派页' },
  033_qiyu: { label: '奇遇', category: 'world_content', png: '/assets/icons/png256/033_qiyu_奇遇.png', webp: '/assets/icons/webp512/033_qiyu_奇遇.webp', route: '跑图/事件页' },
  034_weapon: { label: '武器', category: 'equipment', png: '/assets/icons/png256/034_weapon_武器.png', webp: '/assets/icons/webp512/034_weapon_武器.webp', route: '背包页/武器分类' },
  035_armor: { label: '护具', category: 'equipment', png: '/assets/icons/png256/035_armor_护具.png', webp: '/assets/icons/webp512/035_armor_护具.webp', route: '背包页/护具分类' },
  036_medicine: { label: '药物', category: 'equipment', png: '/assets/icons/png256/036_medicine_药物.png', webp: '/assets/icons/webp512/036_medicine_药物.webp', route: '背包页/药物分类' },
  037_famen: { label: '法门', category: 'martial_arts', png: '/assets/icons/png256/037_famen_法门.png', webp: '/assets/icons/webp512/037_famen_法门.webp', route: '武学页/法门分类' },
  038_shenfa: { label: '身法', category: 'martial_arts', png: '/assets/icons/png256/038_shenfa_身法.png', webp: '/assets/icons/webp512/038_shenfa_身法.webp', route: '武学页/身法分类' },
  039_log: { label: '日志', category: 'system', png: '/assets/icons/png256/039_log_日志.png', webp: '/assets/icons/webp512/039_log_日志.webp', route: 'DM端与玩家端/日志页' },
  040_dm_tools: { label: 'DM工具', category: 'dm_tools', png: '/assets/icons/png256/040_dm_tools_DM工具.png', webp: '/assets/icons/webp512/040_dm_tools_DM工具.webp', route: 'DM端/工具页' },
} as const;
