import type { RuleCatalog } from "./schema";
import { validateRuleCatalog } from "./schema";

export const ruleCatalog: RuleCatalog = {
  moves: [
    {
      id: "WG001",
      name: "破浪横刀",
      category: "外功",
      subtype: "主攻",
      timing: "正式出手",
      minimumDice: 2,
      qiRequirement: "至少1阳",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "失势"],
      rangeAndEquipment: "近身人物目标；主手刀或同类短兵",
      baseEffect: "造成气血4点",
      slotTriggers: ["阳值≥7：追加气血3点", "合值≥10：目标退距1档", "阴阳差≥5：自身破口1层"],
    },
    {
      id: "WG002",
      name: "回潮压刃",
      category: "外功",
      subtype: "主攻",
      timing: "正式出手",
      minimumDice: 3,
      qiRequirement: "至少1阴1阳",
      momentumRequirement: "宽势",
      allowedMomentum: ["阳盛", "合势", "圆融"],
      rangeAndEquipment: "近身人物目标；主手刀",
      baseEffect: "造成气血5点",
      slotTriggers: ["阳值≥8：追加气血3点", "合值≥12：目标锁气中1枚最低点气骰入息库"],
    },
    {
      id: "WG003",
      name: "分涛断势",
      category: "外功",
      subtype: "拆招",
      timing: "正式出手",
      minimumDice: 3,
      qiRequirement: "至少1阴1阳",
      momentumRequirement: "中势",
      allowedMomentum: ["阴盛", "合势", "圆融"],
      rangeAndEquipment: "近身人物目标；刀、剑、短兵均可",
      baseEffect: "目标当前势转入失势，或关闭目标1项轻前置许可",
      slotTriggers: ["阴值≥8：目标由当前势转入失势", "合值≥14：目标本次动作不成招"],
    },
    {
      id: "WG004",
      name: "收刀归息",
      category: "外功",
      subtype: "收式",
      timing: "正式出手",
      minimumDice: 2,
      qiRequirement: "任意气性",
      momentumRequirement: "宽势",
      allowedMomentum: ["阴盛", "阳盛", "合势", "圆融"],
      rangeAndEquipment: "自己；需持刀或可收束姿态",
      baseEffect: "自身破口-1或迟滞-1（二选一）",
      slotTriggers: ["阴值≥7：额外降低1层轻交锋状态"],
    },
  ],
  responses: [
    {
      id: "RG001",
      moveId: "WG001",
      name: "破浪横刀",
      responseType: "截击",
      timing: "宣言后、配置前",
      minimumDice: 2,
      qiRequirement: "至少1阳",
      allowedMomentum: ["阳盛", "合势", "失势"],
      baseEffect: "目标1枚锁气本次不能进入阳槽",
      afterMomentum: "阳盛",
    },
    {
      id: "RG002",
      moveId: "WG001",
      name: "破浪横刀",
      responseType: "应招",
      timing: "成招后、落果前",
      minimumDice: 2,
      qiRequirement: "至少1阳",
      allowedMomentum: ["阳盛", "合势", "圆融"],
      baseEffect: "抵消气血3点",
      afterMomentum: "不改势",
    },
    {
      id: "RG003",
      moveId: "WG002",
      name: "回潮压刃",
      responseType: "截击",
      timing: "宣言后、配置前",
      minimumDice: 3,
      qiRequirement: "至少1阴1阳",
      allowedMomentum: ["阳盛", "合势"],
      baseEffect: "关闭目标本次退距附加效果",
      afterMomentum: "合势",
    },
    {
      id: "RG004",
      moveId: "WG003",
      name: "分涛断势",
      responseType: "截击",
      timing: "宣言后、配置前",
      minimumDice: 3,
      qiRequirement: "至少2阴",
      allowedMomentum: ["阴盛", "圆融"],
      baseEffect: "目标本次势条件视为不满足",
      afterMomentum: "阴盛",
    },
  ],
  quickActions: [
    {
      id: "BX001",
      name: "移步",
      type: "出手便行",
      timing: "自己回合",
      minimumDice: 1,
      qiRequirement: "任意",
      permission: "自己；合法空间",
      effect: "改变1档位置或取得明确站位",
      limit: "不能穿越强封锁；不能稳定脱离纠缠",
      resourceFlow: "已用气骰入息库",
    },
    {
      id: "BX002",
      name: "整身",
      type: "出手便行",
      timing: "自己回合",
      minimumDice: 1,
      qiRequirement: "任意",
      permission: "自己；姿态散乱、倒地、迟滞或轻破口",
      effect: "起身，或迟滞-1，或关闭轻破口（二选一）",
      limit: "不能清强状态",
      resourceFlow: "已用气骰入息库",
    },
    {
      id: "BX003",
      name: "援手",
      type: "出手便行",
      timing: "自己回合",
      minimumDice: 1,
      qiRequirement: "任意",
      permission: "相邻同伴或物件；无人强争夺",
      effect: "扶起、递物、拉离普通边缘（三选一）",
      limit: "不能替同伴应招",
      resourceFlow: "已用气骰入息库",
    },
    {
      id: "BX004",
      name: "取物",
      type: "出手便行",
      timing: "自己回合",
      minimumDice: 1,
      qiRequirement: "任意",
      permission: "可及且未被争夺的物件",
      effect: "取出或拾起一件可及物",
      limit: "有人争夺时改正式出手",
      resourceFlow: "已用气骰入息库",
    },
  ],
};

export function assertRuleCatalogValid(): void {
  const result = validateRuleCatalog(ruleCatalog);
  if (!result.ok) {
    throw new Error(result.errors.join("；"));
  }
}
